# Generated by Django 4.1.7 on 2023-04-11 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('c', 'cafe'), ('r', 'restaurant'), ('p', 'pub')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.users')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_created=datetime.datetime(2023, 4, 11, 19, 47, 48, 500060))),
                ('passport_id', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arrangement.users')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('sp', 'sport'), ('tr', 'traveling'), ('pt', 'painting'), ('cg', 'computer_games'), ('sh', 'shopping'), ('ph', 'photo'), ('ms', 'music')], max_length=2)),
                ('user', models.ManyToManyField(to='arrangement.users')),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.establishments')),
            ],
        ),
        migrations.CreateModel(
            name='Arrangements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.establishments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.users')),
            ],
        ),
    ]
