# Generated by Django 4.1.7 on 2023-04-11 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0002_establishments_userrating_passport_hobbies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 4, 11, 19, 49, 54, 349562)),
        ),
    ]
