# Generated by Django 4.1.7 on 2023-04-13 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0007_alter_passport_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 4, 13, 21, 44, 15, 405535)),
        ),
    ]
