# Generated by Django 4.1.7 on 2023-04-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0008_alter_passport_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
