# Generated by Django 4.1.7 on 2023-04-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0010_users_arrangement_age_d35502_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_age_19c875_idx',
        ),
    ]
