# Generated by Django 4.1.7 on 2023-04-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0011_remove_users_arrangement_age_19c875_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='users',
            name='arrangement_age_7aaaab_idx',
        ),
    ]
