# Generated by Django 4.1.7 on 2023-05-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0014_host_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo_ratings'),
        ),
    ]
