# Generated by Django 4.1.7 on 2023-05-16 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0016_alter_establishmentsrating_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentsrating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5, message='input rating between 1 and 5'), django.core.validators.MinValueValidator(1, message='input rating between 1 and 5')]),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5, message='input rating between 1 and 5'), django.core.validators.MinValueValidator(1, message='input rating between 1 and 5')]),
        ),
    ]
