name: Django CI
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: copy project
      - uses: actions/checkout@v3
      - name: install python
      - uses: actions/setup-python@v4
      
